### ISSUE TITLE
citing of published AEBRs

### ISSUE THREAD

**Issue by katrin-berkenbusch** [dragonfly-science/bibliography#4]
Do we want to include the url and last-check date? We currently have a mixture of AEBR citations with and without this info.

**Comment by katrin-berkenbusch** [comment]
and the bib keys should include the number of pages for each report.

**Comment by katrin-berkenbusch** [comment]
If the websites are included, they should finish with a full stop (at the end of each citation).

**Comment by edwardabraham** [comment]
Good point. The process would be that when a report is being prepared, someone (author/editor) should check that each URL works and then update the lastchecked date.  Our approach to maintaining the bibliography is to update the references that are relevant to each publication, rather than going through the whole file, so I am going to close this as a bibliography issue. But please bear it in mind during report preparation  :smile_cat:
